# Generated by Django 4.1.7 on 2023-03-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_topic_delete_roadmaptopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
