# Generated by Django 4.1.7 on 2023-03-17 16:33

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.user_directory_path, verbose_name='Фото профиля'),
        ),
    ]
