# Generated by Django 4.1.6 on 2023-03-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedHomeworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Удалено')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(None, 'Выберите значение'), ('task', 'Задача'), ('refactor', 'Рефакторинг'), ('tests', 'Тесты'), ('other', 'Other')], max_length=15, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('mark', models.PositiveIntegerField(default=10, verbose_name='Максимальная оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дэдлайн')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Это черновик')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', related_query_name='homeworks', to='homeworks.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-created_at', 'name'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.CheckConstraint(check=models.Q(('mark__lte', 1000)), name='homeworks_homework_max_mark_constraint'),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.UniqueConstraint(condition=models.Q(('type__isnull', False)), fields=('name', 'type'), name='homeworks_homework_name_type_unique_constraint'),
        ),
    ]
