# Generated by Django 4.1.6 on 2023-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_alter_homework_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дэдлайн'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='mark',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальная оценка'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='topic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
