# Generated by Django 4.1.6 on 2023-02-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_alter_homework_options_alter_homework_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-created_at'], 'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
    ]
