# Generated by Django 4.1.6 on 2023-02-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0005_homework_type_alter_homework_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.RemoveField(
            model_name='homework',
            name='topic',
        ),
        migrations.AlterField(
            model_name='homework',
            name='type',
            field=models.CharField(blank=True, choices=[(None, 'Выберите значение'), ('task', 'Задача'), ('refactor', 'Рефакторинг'), ('tests', 'Тесты'), ('other', 'Other')], max_length=15, null=True),
        ),
    ]
