# Generated by Django 4.1.6 on 2023-02-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0006_topic_remove_homework_topic_alter_homework_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homeworks.topic'),
        ),
    ]
