# Generated by Django 4.1.6 on 2023-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_profile_student'),
        ('homeworks', '0008_alter_homework_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='students',
            field=models.ManyToManyField(related_name='homeworks', to='core.student'),
        ),
    ]
