# Generated by Django 4.1.6 on 2023-02-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0009_homework_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', 'name'], 'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('type', 'name')},
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.CheckConstraint(check=models.Q(('mark__lte', 1000)), name='homeworks_homework_max_mark_constraint'),
        ),
    ]
