# Generated by Django 4.1.6 on 2023-02-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0010_alter_homework_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.UniqueConstraint(condition=models.Q(('type__isnull', False)), fields=('name', 'type'), name='homeworks_homework_name_type_unique_constraint'),
        ),
    ]
